#!/usr/bin/env bash

playbook='---
- hosts: localhost
  roles:'

while IFS= read -r role
do
    if ! find "$role" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        -execdir [[ -p 'tasks/main.yml' ]] \; \
        2> /dev/null
    then
        printf 'ansible: %s is not a role\n' "$role"
        continue
    fi
    playbook+="
    - role: '$role'"
done < "$1"

ansible-playbook <(printf '%s' "$playbook") --ask-become-pass
