#!/usr/bin/env bash

playbook='- hosts: localhost
  roles:'

while IFS= read -r role; do
    playbook+="
    - {role: '$role'}"
done < "$1"

ansible-playbook <(printf '%s' "$playbook") --ask-become-pass
