#!/usr/bin/env bash

playbook="- hosts: localhost
  roles:"

while IFS= read -r role
do
    if ! find "$role" \
        -maxdepth 1 \
        -type d \
        -exec test -f '{}/tasks/main.yml' \; \
        2> /dev/null
    then
        printf 'ansible-roles: %s is not a directory\n' "$role"
        continue
    fi
    playbook+="
    - role: '$role'"
done < $1

ansible-playbook <(printf '%s' "$playbook") --ask-become-pass
