- name: Install Yabai with homebrew
  community.general.homebrew:
    name: yabai
    state: present
  notify:
    # - Uninstall Yabai service
    - Load scripting additions
    - Install Yabai service
    - Start Yabai service
