- name: Build Neovim
  ansible.builtin.command:
    chdir: "{{ ansible_env.HOME }}/neovim"
    cmd: make CMAKE_BUILD_TYPE=Release
  changed_when: true

- name: Install Neovim
  become: true
  ansible.builtin.command:
    chdir: "{{ ansible_env.HOME }}/neovim"
    cmd: make install
  changed_when: true
