- name: Archlinux | Copy Librespot User Service
  become: true
  ansible.builtin.copy:
    src: librespot.user.service
    dest: /usr/lib/systemd/user/librespot.user.service
    owner: root
    group: root
    mode: "0644"

- name: Archlinux | Enable Librespot User Service
  become_user: "{{ ansible_env.USER }}"
  ansible.builtin.systemd_service:
    name: librespot.user.service
    scope: user
    daemon_reload: true
    state: stopped
    enabled: false
