- name: Git clone Neovim
  ansible.builtin.git:
    repo: "git@github.com:neovim/neovim.git"
    dest: "{{ ansible_env.HOME }}/neovim"
    version: "stable"
    depth: 1
  notify:
    - Build Neovim
    - Install Neovim
